name: Build Maven
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: true
  image_name:
    description: "Name of the docker image"
    required: true
  tag_name:
    description: "Name of the docker tag"
    required: true
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
      shell: bash
    - name: Build Docker File
      run: docker build . --file ${{ inputs.dockerfile_path }} --tag ${{ inputs.tag_name }}:${{ inputs.tag_name }}
      shell: bash