name: Push Docker Image
description: Re-tag the Docker Image and pushes it to Docker Hub
inputs:
  old_image_name:
    description: "Name of the old docker image to be used in the tag"
    required: true
  old_version_name:
    description: "Name of the old docker version to be used in the tag"
    required: true
  docker_username:
    description: "Docker User Username"
    required: true
  docker_token:
    description: "Docker User Token"
    required: true
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}
    - name: Re-tag Image
      run: docker tag ${{ inputs.old_image_name }}:${{ inputs.old_version_name }} ${{ inputs.docker_username }}/${{ inputs.old_image_name }}:${{ inputs.old_version_name }}
      shell: bash
    - name: Push Image to Docker Hub
      run: docker push ${{ inputs.docker_username }}/${{ inputs.old_image_name }}:${{ inputs.old_version_name }}
      shell: bash
